### ISSUE TITLE
Make godot-logger singleton script as a godot addon

### ISSUE THREAD

**Issue by MrZak-dev** [KOBUGE-Games/godot-logger#25]
Currently, godot-logger is a singleton script that needs to be added manually to the project settings.
I propose to make godot-logger a Godot addon that can be installed from the `AssetLib`.

The plugin can do :
- install logger files to `addons` directory. 
- Automatically once installed, add the script as a singleton to the project.

**Comment by Calinou** [comment]
See this for an example of a `plugin.gd` that adds/removes an autoload as needed: https://github.com/Calinou/godot-photo-mode-demo/blob/master/addons/photo_mode/plugin.gd
