### ISSUE TITLE
Logger Crashing on Buffer Flush

### ISSUE THREAD

**Issue by ogrady** [KOBUGE-Games/godot-logger#27]
Hi,

there appears to be some leftovers from converting godot-logger from Godot 3.x to 4.x:

[Flushing the buffer](https://github.com/KOBUGE-Games/godot-logger/blob/master/logger.gd#L101) checks the result of `file.open(...)` to see if there was an error. As [`FileAccess.open` now returns the file handle](https://docs.godotengine.org/en/stable/classes/class_fileaccess.html#class-fileaccess-method-open) as opposed to how it [returned an error code in 3.x](https://docs.godotengine.org/en/3.6/classes/class_file.html#class-file-method-open), we will always land in the following error-handler – which will fail itself, as the resulting file handle is not a valid parameter for the `%d` string formatter.

```
[ERROR] [logger] Could not open the 'user://logfile.log' log file; exited with error <FileAccess#-9223371805681513908>.
```
(output when I fix the `%d` issue)

Following the GD doc, you'll probably want to use [`get_open_error`](https://docs.godotengine.org/en/stable/classes/class_fileaccess.html#class-fileaccess-method-get-open-error) instead for this handling.

**Comment by SirMoM** [comment]
Would something like this fix the issue?
https://github.com/SirMoM/godot-logger/commit/3ce86ddd420269d73502891265c0842a81364afd

**Comment by ogrady** [comment]
Hi SirMoM,

this looks good on first glance, but I'd have to try it out to be certain and I am currently traveling with no access to a proper computer. I will check it out once I am back. In any case, thanks for looking into it!

Best,
Daniel

**Comment by SirMoM** [comment]
If it works for you, I would create a PR @ogrady

**Comment by ogrady** [comment]
Hi SirMoM,

sorry for the delay, I have only just returned from my travel. 

Thank you for looking into the matter! I have tried your fork and I'm afraid it is not runnable under Godot 4.x in its current state. For example, there are bunch of undeclared variables, `get_open_error` is a static method from `FileAccess`, `seek_end` not being a method of file access. I have stopped after that, so there might be a couple more.
But at this point, it doesn't look like the fork provides a proper fix, I'm afraid.

Best,
Daniel

**Comment by ogrady** [comment]
Hi @SirMoM ,

is there any progress on this issue? Is it planned to support GD4.x from the godot-logger anyway?

Best,
Daniel

**Comment by SirMoM** [comment]
Hey @ogrady,

sorry for been away for a while.
I created a PR #28 that should fix this issue.

If @akien-mga or you could test it, it can be merged :w

**Comment by ogrady** [comment]
Hi @SirMoM ,

I gave your changes a whirl and the logger seems to be back in working shape now. Thank you!
